feat(yabai): configure yabai codecert/sudo as post-update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -17,7 +17,33 @@ else
     echo "ERROR: could not determine package manager."
     exit 1
 fi
-# TODO: add eg. `port cut_leaves` and other pruning? or new prune script?
+
+echo "Running post-upgrade steps..."
+if which zypper >/dev/null; then
+    :
+elif which port >/dev/null; then
+    # TODO: add eg. `port cut_leaves` and other pruning? or new prune script?
+    which yabai && {
+        sudo codesign -fs 'yabai-cert' /opt/local/bin/yabai
+
+        # Grant sudo access for yabai
+        echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 "$(which yabai)") --load-sa" | sudo tee /etc/sudoers.d/yabai
+
+        sudo yabai --load-sa
+        yabai --restart-service
+    }
+
+    which skhd && {
+        skhd --restart-service
+    }
+elif which apt-get >/dev/null; then
+    :
+elif which dnf >/dev/null; then
+    :
+else
+    echo "ERROR: could not determine package manager."
+    exit 1
+fi
 
 echo "Upgrading cargo packages..."
 cargo-upgrade
